import { profile } from "console";

export const friends = [
    {
        name: "Alyisa Bravery",
        nickname: "",
        profilePic: "/profile/alysia.png",
        isOnline: true,
        hasIcon: "",
        isPinned: true,
        newMessages: 1,
    },
    {
        name: "Charlotte Hale",
        nickname: "Charlotte demon",
        profilePic: "/profile/charlotte.png",
        isOnline: false,
        hasIcon: "Demon",
        isPinned: false,
        newMessages: 0,
    },
    {
        name: "Moana Waialiki",
        nickname: "Moana Jungle",
        profilePic: "/profile/moana.png",
        isOnline: true,
        hasIcon: "",
        isPinned: false,
        newMessages: 1,
    },
    {
        name: "David Goliath",
        nickname: "Davey",
        profilePic: "/profile/davey.png",
        isOnline: false,
        hasIcon: "",
        isPinned: false,
        newMessages: 0,
    },
    {
        name: "Alyisa Bravery",
        nickname: "",
        profilePic: "/profile/alysia.png",
        isOnline: true,
        hasIcon: "",
        isPinned: true,
        newMessages: 1,
    },
    {
        name: "Charlotte Hale",
        nickname: "Charlotte demon",
        profilePic: "/profile/charlotte.png",
        isOnline: false,
        hasIcon: "Demon",
        isPinned: false,
        newMessages: 0,
    },
    {
        name: "Moana Waialiki",
        nickname: "Moana Jungle",
        profilePic: "/profile/moana.png",
        isOnline: true,
        hasIcon: "",
        isPinned: false,
        newMessages: 1,
    },
    {
        name: "David Goliath",
        nickname: "Davey",
        profilePic: "/profile/davey.png",
        isOnline: false,
        hasIcon: "",
        isPinned: false,
        newMessages: 0,
    },
];